export const ADD_POST ='ADD-POST';
export const CHANGE_VALUE_TEXT_POST ='CHANGE-VALUE-TEXT-POST';
 export const ADD_MESSAGE ='ADD-MESSAGE';
export  const CHANGE_VALUE_NEW_MESSAGE ='CHANGE-VALUE-NEW-MESSAGE';